name: Sample
on:
  workflow_dispatch:
jobs:
  Deploy_to_Testserver:
    runs-on: self-hosted
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      #- name: Install Deno
      #  uses: denoland/setup-deno@v2
      #  with:
      #    deno-version: v2.x

      - name: add permisson
        run: sudo chmod +x /actions-runner/Testrunner/_work/Zisty-bot/Zisty-bot/runbot.sh
        shell: bash
      
      - name: restart service
        run: sudo systemctl restart actions.runner.syobosyobonn-Zisty-bot.Testrunner.bot.service
        shell: bash

      - name: Check service status
        run: |
          sudo systemctl status actions.runner.syobosyobonn-Zisty-bot.Testrunner.bot.service --no-pager -l
          echo "--- Last 20 log lines ---"
          sudo journalctl -u actions.runner.syobosyobonn-Zisty-bot.Testrunner.bot.service -n 20 --no-pager
        shell: bash
